"""CLI helper for LaTeX output format."""
from __future__ import annotations

import sys
from pathlib import Path
from typing import IO

from csvdiff.core import DiffResult
from csvdiff.render_latex import render_latex


def _render_to_stream(diff: DiffResult, stream: IO[str]) -> None:
    """Write LaTeX preamble + body to *stream*."""
    stream.write(
        "% Generated by csvdiff-cli\n"
        "% Requires: xcolor, longtable packages\n"
        "\\usepackage{xcolor}\n"
        "\\usepackage{longtable}\n"
        "\n"
    )
    render_latex(diff, stream)


def handle_latex_output(
    diff: DiffResult,
    output_path: str | None,
    *,
    preamble: bool = True,
) -> None:
    """Write LaTeX diff output to *output_path* or stdout.

    Parameters
    ----------
    diff:
        The computed diff result.
    output_path:
        File path to write to, or ``None`` to write to stdout.
    preamble:
        When *True* (default) prepend ``\\usepackage`` declarations.
    """
    if output_path is None:
        if preamble:
            _render_to_stream(diff, sys.stdout)
        else:
            render_latex(diff, sys.stdout)
        return

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        if preamble:
            _render_to_stream(diff, fh)
        else:
            render_latex(diff, fh)
