"""Render a DiffResult as a groff/troff ms document."""
from __future__ import annotations

from io import StringIO
from typing import List

from .core import DiffResult


def _escape(text: str) -> str:
    """Escape special groff characters."""
    text = text.replace("\\", "\\e")
    text = text.replace("-", "\\-")
    return text


def _row_to_cells(row: dict, columns: List[str]) -> str:
    """Format a single row as a tab-separated groff table row."""
    return "\t".join(_escape(str(row.get(c, ""))) for c in columns)


def _render_section(
    buf: StringIO,
    title: str,
    rows: List[dict],
    columns: List[str],
) -> None:
    if not columns:
        return
    buf.write(f".SH {title}\n")
    if not rows:
        buf.write(".PP\n")
        buf.write("No rows.\n")
        return
    # tbl block
    buf.write(".TS\n")
    buf.write("allbox;\n")
    # column format: left-aligned for each column
    fmt = " ".join("l" for _ in columns)
    buf.write(f"{fmt}.\n")
    # header
    buf.write(_row_to_cells({c: c for c in columns}, columns) + "\n")
    for row in rows:
        buf.write(_row_to_cells(row, columns) + "\n")
    buf.write(".TE\n")


def render_groff(diff: DiffResult, preamble: bool = True) -> str:
    """Return a groff ms document representing the diff.

    Parameters
    ----------
    diff:
        The diff result to render.
    preamble:
        When True, include the .TH / document header lines.
    """
    if not diff.columns:
        return ""

    buf = StringIO()

    if preamble:
        buf.write('.TH "CSV DIFF" 1\n')
        buf.write(".\" Generated by csvdiff-cli\n")

    _render_section(buf, "Added Rows", diff.added, diff.columns)
    _render_section(buf, "Removed Rows", diff.removed, diff.columns)

    changed_old = [c["old"] for c in diff.changed]
    changed_new = [c["new"] for c in diff.changed]
    _render_section(buf, "Changed Rows (Before)", changed_old, diff.columns)
    _render_section(buf, "Changed Rows (After)", changed_new, diff.columns)

    return buf.getvalue()
